<!DOCTYPE html>
<html dir="ltr" lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description"
          content="<?= $title ?> page of the personal website of Jan Gabler">

    <link href="styles/style.css" rel="stylesheet">

    <title>Jan Gabler - <?= $title ?></title>

  </head>

  <body>

    <nav class="site-navigation">
      <a href="index.html" class="site-navigation__link">Home</a> |
      <a href="about.html" class="site-navigation__link">About</a> |
      <a href="contact.html" class="site-navigation__link">Contact</a>
    </nav>

    <main class="site-content">
      <?= $content ?>
    </main>

    <hr>

    <footer class="site-footer">
      <p>
        © Copyright 2013 - 2020 Jan Gabler. All rights reserved.
        <br>
        <a href="privacy-policy.html" class="site-footer__link">
          Privacy policy
        </a> -
        <a href="colophon.html" class="site-footer__link">
          Colophon
        </a>
      </p>
    </footer>

  </body>

</html>
