<?php
$title = $title ?? "...";
$content = $content ?? "";
$primaryNavItems = [
    [ "name" => "Home",      "href" => "index.html" ],
    [ "name" => "About",     "href" => "about.html" ],
    [ "name" => "Elsewhere", "href" => "elsewhere.html" ],
];
$secondaryNavItems = [
    [ "name" => "Privacy policy",       "href" => "privacy-policy.html" ],
    [ "name" => "Third-party licenses", "href" => "third-party-licenses.html" ],
    [ "name" => "Back to top",          "href" => "#top" ],
];
$description = sprintf(
    "The %s page of the personal website of Jan Gabler", strtolower($title)
);
?>
<!DOCTYPE html>
<html dir="ltr" lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<?= $description; ?>">

    <link href="styles/style.css" rel="stylesheet">

    <title>Jan Gabler - <?= $title; ?></title>

  </head>

  <body>

    <nav class="site-navigation">
      <ul class="list-inline">

        <?php foreach ($primaryNavItems as $primaryNavItem): ?>

        <li class="list-inline__item list-inline__item--v-separator">
          <a href="<?= $primaryNavItem["href"]; ?>"
             class="site-navigation__link">
            <?= $primaryNavItem["name"]; ?>
          </a>
        </li>

        <?php endforeach; ?>

      </ul>
    </nav>

    <main class="site-content">
      <?= $content ?>
    </main>

    <hr>

    <footer class="site-footer">
      <p class="site-footer__note">
        © Copyright 2013 - <?= date("Y"); ?> Jan Gabler.
        <span class="no-wrap">All rights reserved.</span>
      </p>
      <nav>
        <ul class="list-inline">

          <?php foreach ($secondaryNavItems as $secondaryNavItem): ?>

          <li class="list-inline__item list-inline__item--h-separator">
            <a href="<?= $secondaryNavItem["href"]; ?>"
               class="site-footer__link">
              <?= $secondaryNavItem["name"]; ?>
            </a>
          </li>

          <?php endforeach; ?>

        </ul>
      </nav>
    </footer>

  </body>

</html>
