<?php $title = "About"; ?>

<?php ob_start(); ?>

<h1>About</h1>
<p>
  I’m Jan Gabler, a software developer from <a
  href="https://en.wikipedia.org/wiki/Berlin">Berlin, Germany</a>.
</p>
<p>
  I really like the world of bits & bytes, with all the interesting and smart
  things which are based on them.
</p>
<p>
  Since my early days, I’m interested in computer science, so I’ve turned my
  hobby into a profession. After my apprenticeship as a computer science expert
  in the subject area of system integration and my first jobs, I’ve studied
  business computing and finished it with a master’s degree.
</p>
<p>
  I’m currently working as a software developer and building primarily Java-
  and PHP-based web applications. For detailed information about my
  professional career, have a look at my <a
  href="https://www.linkedin.com/in/jangabler">LinkedIn profile</a>.
</p>
<p>
  Furthermore, I like working with the languages Go, SQL, Markdown and the
  concepts behind hypertext, progressive enhancement and everything as code.
  Usually, I reposit my source code on <a href="https://github.com/jangabler">
  GitHub</a>.
</p>

<?php $content = ob_get_clean(); ?>

<?php include "templates/page.phtml"; ?>
