<?php $title = "Colophon"; ?>

<?php ob_start(); ?>

<h1>Colophon</h1>
<p>The following typefaces are used:</p>
<ul>
  <li>
    Source Sans Pro ( <a href=
    "https://github.com/adobe-fonts/source-sans-pro/blob/release/LICENSE.md">
    SIL Open Font License 1.1</a> )
  </li>
  <li>
    Source Serif Pro ( <a href=
    "https://github.com/adobe-fonts/source-serif-pro/blob/release/LICENSE.md">
    SIL Open Font License 1.1</a> )
  </li>
</ul>

<?php $content = ob_get_clean(); ?>

<?php include "_layout.phtml"; ?>
