<?php $title = "Home"; ?>

<?php ob_start(); ?>

<h1>Hello and welcome, I'm Jan! 👋</h1>
<p>
  I really like the world of bits & bytes, with all the interesting and smart
  things which are based on them.
</p>
<p>
  Since my early days, I'm interested in computer science, so I've turned my
  hobby into a profession. After my apprenticeship as a computer science expert
  in the subject area of system integration and my first jobs, I've studied
  business computing and finished it with a master's degree.
</p>
<p>
  I'm currently working as a software developer and building primarily Java-
  and PHP-based web applications.
</p>
<p>
  Furthermore, I like working with the languages Go, SQL, Markdown and the
  concepts behind hypertext and everything as code.
</p>
<p>
  Perhaps you're interested in my <a href="https://github.com/jangabler">code
  </a> or <a rel="me" href="https://mastodon.social/@jangabler">toots</a> ;-)
</p>
<p>
  <b>Have a great day!</b>
</p>

<?php $content = ob_get_clean(); ?>

<?php include "_layout.phtml"; ?>
