<?php $title = "Home"; ?>

<?php ob_start(); ?>

<section class="welcome__text">
  <h1>Hello and welcome, <span class="no-wrap">I’m Jan! 👋</span></h1>
  <p>
    This is my spot on the World Wide Web — my personal website. Here you’ll
    find some information <a href="about.html">about me</a>, what <a
    href="uses.html">I use</a> and also leads you to <a href="elsewhere.html">
    me elsewhere</a> on the internet.
  </p>
  <p>
    <b>Have a great day!</b>
  </p>
</section>

<picture class="welcome__portrait">
  <source srcset="img/me.webp" type="image/webp">
  <img src="img/me.png" alt="Portrait of me" height="192" width="192">
</picture>

<?php $content = ob_get_clean(); ?>

<?php include "templates/page.phtml"; ?>
