<?php $title = "Privacy policy"; ?>

<?php ob_start(); ?>

<h1>Privacy policy</h1>
<p>
  To put it in a nutshell, this website doesn't track anything, doesn't use any 
  cookies and also doesn't collect any data in server logs!
</p>
<nav class="site-navigation">
  <a href="index.html" class="site-navigation__link">← Back to home</a>
</nav>

<?php $content = ob_get_clean(); ?>

<?php include "_layout.phtml"; ?>
