<?php $title = "Third-party licenses"; ?>

<?php ob_start(); ?>

<h1>Third-party licenses</h1>
<p>The following typefaces are used:</p>
<ul>
  <li>
    “Source Sans Pro” applies the <a href=
    "https://github.com/adobe-fonts/source-sans-pro/blob/release/LICENSE.md">
    SIL Open Font License 1.1</a>
  </li>
  <li>
    “Source Serif Pro” applies the <a href=
    "https://github.com/adobe-fonts/source-serif-pro/blob/release/LICENSE.md">
    SIL Open Font License 1.1</a>
  </li>
    <li>
    “Source Code Pro” applies the <a href=
    "https://github.com/adobe-fonts/source-code-pro/blob/release/LICENSE.md">
    SIL Open Font License 1.1</a>
  </li>
</ul>

<?php $content = ob_get_clean(); ?>

<?php include "templates/page.phtml"; ?>
