<?php $title = "Uses"; ?>

<?php ob_start(); ?>

<h1>Uses</h1>
<p>
  Here you can find the most important <a href="#hardware">hard-</a> & <a
  href="#software">software</a> as well as <a href="#services">services</a> I
  use. This page is inspired by the <a href="https://uses.tech/">uses.tech</a>
  list.
</p>

<h2 id="hardware">Hardware</h2>
<ul>
  <li>
    Apple MacBook Pro 13.3″
    <small class="greyed-out">from early 2015</small>
  </li>
  <li>
    Lenovo ThinkPad L420
    <small class="greyed-out">runs on Ubuntu Linux</small>
  </li>
  <li>
    Raspberry Pi Model B (Revision 2.0)
    <small class="greyed-out">with 512 MB RAM</small>
  </li>
  <li>
    LG Flatron E2290V 21.5″
    <small class="greyed-out">damn old and still no defective pixel</small>
  </li>
  <li>
    Apple Magic Keyboard
    <small class="greyed-out">with a German keyboard layout</small>
  </li>
  <li>
    Apple Magic Mouse 2
    <small class="greyed-out">doubtless the charging is a massive UX design
    fail</small>
  </li>
  <li>
    Apple iPhone XR
    <small class="greyed-out">with 64 GB storage capacity</small>
  </li>
</ul>

<h2 id="software">Software</h2>
<ul>
  <li>
    Git
    <small class="greyed-out">as version control system of my source code
    </small>
  </li>
  <li>
    Sublime Text
    <small class="greyed-out">as text editor
    (see <a href="https://raw.githubusercontent.com/jangabler/dotfiles/master/configuration/Preferences.sublime-settings">
    Preferences.sublime-settings</a>)</small>
  </li>
  <li>
    PhpStorm
    <small class="greyed-out">as PHP and JavaScript IDE</small>
  </li>
  <li>
    GoLand
    <small class="greyed-out">as Golang IDE</small>
  </li>
  <li>
    Eclipse
    <small class="greyed-out">as Java IDE</small>
  </li>
  <li>
    JetBrains Mono
    <small class="greyed-out">as monospaced font in the text editor and IDE’s
    </small>
  </li>
  <li>
    Google Chrome
    <small class="greyed-out">as main web browser (extensions: uBlock Origin &
    Markdown Viewer)</small>
  </li>
  <li>
    Mozilla Firefox
    <small class="greyed-out">as development web browser</small>
  </li>
  <li>
    Safari
    <small class="greyed-out">as development web browser too</small>
  </li>
  <li>
    Lynx
    <small class="greyed-out">just for fun to browse the web text-based on the
    CLI</small>
  </li>
  <li>
    Zsh
    <small class="greyed-out">as shell of my choice, to run all the CLI tools
    (see <a href="https://raw.githubusercontent.com/jangabler/dotfiles/master/configuration/.zshrc">
    .zshrc</a>)</small>
  </li>
  <li>
    Homebrew
    <small class="greyed-out">as package manager for GUI and CLI applications
    (see <a href="https://raw.githubusercontent.com/jangabler/dotfiles/master/installation/brew.sh">
    brew.sh</a>)</small>
  </li>
  <li>
    NetNewsWire
    <small class="greyed-out">as feed reader</small>
  </li>
  <li>
    iA Writer
    <small class="greyed-out">as markdown editor</small>
  </li>
  <li>
    MiKTeX
    <small class="greyed-out">as LaTeX editor</small>
  </li>
  <li>
    KeePassXC
    <small class="greyed-out">as password manager</small>
  </li>
</ul>

<h2 id="services">Services</h2>
<ul>
  <li>
    GitHub
    <small class="greyed-out">for source code management</small>
  </li>
  <li>
    Spotify
    <small class="greyed-out">for music streaming</small>
  </li>
  <li>
    Dropbox
    <small class="greyed-out">for file hosting</small>
  </li>
  <li>
    WhatsApp
    <small class="greyed-out">for instant messaging</small>
  </li>
</ul>

<?php $content = ob_get_clean(); ?>

<?php include "templates/page.phtml"; ?>
