<?php $title = "Uses"; ?>

<?php ob_start(); ?>

<h1>Uses</h1>
<p>
  Here you can find the most important <a href="#hardware">hard-</a> and <a
  href="#software">software</a> I use. This page is inspired by the <a
  href="https://uses.tech/">uses.tech</a> list.
</p>

<h2 id="hardware">Hardware</h2>
<ul>
  <li>
    MacBook Pro 13.3″
    <small class="greyed-out">from early 2015</small>
  </li>
  <li>
    LG Flatron E2290V 21.5″
    <small class="greyed-out">damn old and still no defective pixel</small>
  </li>
  <li>
    Magic Keyboard
    <small class="greyed-out">with a German keyboard layout</small>
  </li>
  <li>
    Magic Mouse 2
    <small class="greyed-out">doubtless the charging is a massive UX design
    fail</small>
  </li>
  <li>
    iPhone XR 64 GB
  </li>
</ul>

<h2 id="software">Software</h2>
<ul>
  <li>
    Sublime Text
    <small class="greyed-out">as text editor</small>
  </li>
  <li>
    PhpStorm
    <small class="greyed-out">as PHP and JavaScript IDE</small>
  </li>
  <li>
    GoLand
    <small class="greyed-out">as Golang IDE</small>
  </li>
  <li>
    Eclipse
    <small class="greyed-out">as Java IDE</small>
  </li>
  <li>
    JetBrains Mono
    <small class="greyed-out">as monospaced font in the text editor and IDE’s
    </small>
  </li>
  <li>
    Google Chrome
    <small class="greyed-out">as main web browser</small>
  </li>
  <li>
    Mozilla Firefox
    <small class="greyed-out">as development web browser</small>
  </li>
  <li>
    Safari
    <small class="greyed-out">as development web browser too</small>
  </li>
  <li>
    Lynx
    <small class="greyed-out">just for fun to browse the web text-based on the
    CLI</small>
  </li>
  <li>
    Zsh
    <small class="greyed-out">as shell of my choice, to run all the CLI tools
    </small>
  </li>
  <li>
    Homebrew
    <small class="greyed-out">as package manager for GUI and CLI applications
    </small>
  </li>
  <li>
    NetNewsWire
    <small class="greyed-out">as feed reader</small>
  </li>
  <li>
    KeePassXC
    <small class="greyed-out">as password manager</small>
  </li>
  <li>
    Spotify
    <small class="greyed-out">as music streaming service</small>
  </li>
</ul>

<?php $content = ob_get_clean(); ?>

<?php include "_layout.phtml"; ?>
