<?php
$currentFile = sprintf("%s.html", basename($_SERVER["SCRIPT_NAME"], ".phtml"));

$canonicalUrl = sprintf(
    "https://www.jangabler.de/%s",
    strcmp($currentFile, "index.html") == 0 ? "" : $currentFile
);

$title = $title ?? "...";

$description = sprintf(
    "The %s page of Jan Gabler’s personal website", strtolower($title)
);

$content = $content ?? "";

$primaryNavItems = [
    [ "name" => "Home",      "href" => "index.html" ],
    [ "name" => "About",     "href" => "about.html" ],
    [ "name" => "Uses",      "href" => "uses.html" ],
    [ "name" => "Elsewhere", "href" => "elsewhere.html" ],
];

$secondaryNavItems = [
    [ "name" => "Privacy policy",       "href" => "privacy-policy.html" ],
    [ "name" => "Third-party licenses", "href" => "third-party-licenses.html" ],
    [ "name" => "Back to top",          "href" => "#top" ],
];
?>
<!DOCTYPE html>
<html dir="ltr" lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<?= $description; ?>">

    <link href="<?= $canonicalUrl; ?>" rel="canonical">
    <link href="img/favicon.svg" rel="icon" type="image/svg+xml">
    <link href="fonts/SourceSansVariable-Roman.ttf.woff2" rel="preload"
          as="font" type="font/woff2" crossorigin>
    <link href="fonts/SourceSerifVariable-Roman.ttf.woff2" rel="preload"
          as="font" type="font/woff2" crossorigin>
    <link href="styles/style.css" rel="stylesheet">

    <title><?= $title; ?> - Jan Gabler </title>

  </head>

  <body class="layout">

    <nav class="layout__item site-navigation">
      <ul class="site-navigation__list">

        <?php foreach ($primaryNavItems as $primaryNavItem): ?>

        <li class="site-navigation__item site-navigation__item--separator">
          <a href="<?= $primaryNavItem["href"]; ?>"
             class="site-navigation__link">
            <?= $primaryNavItem["name"]; ?>
          </a>
        </li>

        <?php endforeach; ?>

      </ul>
    </nav>

    <main class="layout__item site-content
    <?php if (strcmp($title, "Home") == 0): ?>welcome<?php endif; ?>
    ">
      <?= $content; ?>
    </main>

    <footer class="layout__item site-footer">
      <p class="site-footer__note">
        © Copyright 2013 - <?= date("Y"); ?> Jan Gabler.
        <span class="no-wrap">All rights reserved.</span>
      </p>
      <nav>
        <ul class="site-footer__list">

          <?php foreach ($secondaryNavItems as $secondaryNavItem): ?>

          <li class="site-footer__item site-footer__item--separator">
            <a href="<?= $secondaryNavItem["href"]; ?>"
               class="site-footer__link">
              <?= $secondaryNavItem["name"]; ?>
            </a>
          </li>

          <?php endforeach; ?>

        </ul>
      </nav>
    </footer>

  </body>

</html>
